<?php

return [
    'general' => [
        'site_name' => ['type' => 'string', 'label' => 'Site Name', 'default' => 'ACCO Pakistan'],
        'tagline' => ['type' => 'string', 'label' => 'Tagline', 'default' => 'Architecture, Engineering & Construction'],
        'logo' => ['type' => 'image', 'label' => 'Logo — Light (white, for dark/transparent backgrounds)'],
        'logo_dark' => ['type' => 'image', 'label' => 'Logo — Dark (navy, for light/white backgrounds)'],
        'favicon' => ['type' => 'image', 'label' => 'Favicon'],
        'phone' => ['type' => 'string', 'label' => 'UAN'],
        'mobile' => ['type' => 'string', 'label' => 'Mobile'],
        'email' => ['type' => 'string', 'label' => 'Email'],
        'address' => ['type' => 'text', 'label' => 'Address'],
        'business_hours' => ['type' => 'string', 'label' => 'Business Hours', 'default' => 'Mon - Sat: 9:00 AM - 6:00 PM'],
        'google_map_embed' => ['type' => 'text', 'label' => 'Google Map Embed Code (paste the full <iframe> embed code from Google Maps)'],
        'footer_seo_text' => [
            'type' => 'text',
            'label' => 'Footer Tagline (short, keyword-rich — shown under the logo site-wide)',
            'default' => 'Architecture, Engineering & Construction firm in Lahore, Pakistan — serving Rawalpindi, Karachi & Islamabad.',
        ],
    ],
    'social' => [
        'facebook_url' => ['type' => 'string', 'label' => 'Facebook URL'],
        'instagram_url' => ['type' => 'string', 'label' => 'Instagram URL'],
        'linkedin_url' => ['type' => 'string', 'label' => 'LinkedIn URL'],
        'youtube_url' => ['type' => 'string', 'label' => 'YouTube URL'],
        'twitter_url' => ['type' => 'string', 'label' => 'X (Twitter) URL'],
        'whatsapp_number' => ['type' => 'string', 'label' => 'WhatsApp Number'],
    ],
    'seo' => [
        'default_meta_title' => ['type' => 'string', 'label' => 'Default Meta Title'],
        'default_meta_description' => ['type' => 'text', 'label' => 'Default Meta Description'],
        'default_og_image' => ['type' => 'image', 'label' => 'Default OG Image'],
        'google_site_verification' => ['type' => 'string', 'label' => 'Google Site Verification Code'],
        'robots_txt_extra' => ['type' => 'text', 'label' => 'Extra robots.txt Rules'],
    ],
    'integrations' => [
        'google_analytics_id' => ['type' => 'string', 'label' => 'Google Analytics ID (GA4)'],
        'google_tag_manager_id' => ['type' => 'string', 'label' => 'Google Tag Manager ID'],
        'facebook_pixel_id' => ['type' => 'string', 'label' => 'Facebook Pixel ID'],
        'recaptcha_site_key' => ['type' => 'string', 'label' => 'reCAPTCHA Site Key'],
    ],
    'homepage' => [
        'hero_heading' => ['type' => 'string', 'label' => 'Hero Heading', 'default' => 'Building Tomorrow\'s Pakistan, Today'],
        'hero_subheading' => ['type' => 'text', 'label' => 'Hero Subheading', 'default' => 'Architecture, Engineering, and Construction excellence from concept to commissioning.'],
        'hero_image' => ['type' => 'image', 'label' => 'Hero Background Image'],
        'intro_heading' => ['type' => 'string', 'label' => 'Intro Heading', 'default' => 'A Complete Turnkey Partner'],
        'intro_content' => ['type' => 'text', 'label' => 'Intro Content'],
        'years_experience' => ['type' => 'integer', 'label' => 'Years of Experience', 'default' => 15],
        'projects_completed' => ['type' => 'integer', 'label' => 'Projects Completed', 'default' => 120],
        'happy_clients' => ['type' => 'integer', 'label' => 'Happy Clients', 'default' => 80],
        'awards_won' => ['type' => 'integer', 'label' => 'Awards Won', 'default' => 12],
    ],
    'about' => [
        'about_heading' => ['type' => 'string', 'label' => 'About Heading', 'default' => 'About ACCO Pakistan'],
        'about_content' => ['type' => 'text', 'label' => 'About Content'],
        'mission' => ['type' => 'text', 'label' => 'Mission Statement'],
        'vision' => ['type' => 'text', 'label' => 'Vision Statement'],
        'about_image' => ['type' => 'image', 'label' => 'About Image'],
    ],
    'why_choose_us' => [
        'why1_title' => ['type' => 'string', 'label' => 'Reason 1 Title', 'default' => 'Turnkey Delivery'],
        'why1_text' => ['type' => 'text', 'label' => 'Reason 1 Text', 'default' => 'Single point of accountability from concept design through construction and commissioning.'],
        'why2_title' => ['type' => 'string', 'label' => 'Reason 2 Title', 'default' => 'In-House Engineering'],
        'why2_text' => ['type' => 'text', 'label' => 'Reason 2 Text', 'default' => 'Architecture, structural, and MEP engineering under one roof for faster, coordinated delivery.'],
        'why3_title' => ['type' => 'string', 'label' => 'Reason 3 Title', 'default' => 'On-Time Performance'],
        'why3_text' => ['type' => 'text', 'label' => 'Reason 3 Text', 'default' => 'Disciplined project management and cost control keep every project on schedule and on budget.'],
        'why4_title' => ['type' => 'string', 'label' => 'Reason 4 Title', 'default' => 'Quality & Safety'],
        'why4_text' => ['type' => 'text', 'label' => 'Reason 4 Text', 'default' => 'Rigorous quality assurance and site safety standards on every project we deliver.'],
    ],
    'process' => [
        'step1_title' => ['type' => 'string', 'label' => 'Step 1 Title', 'default' => 'Consultation'],
        'step1_text' => ['type' => 'text', 'label' => 'Step 1 Text', 'default' => 'We understand your vision, requirements, and budget to shape the project brief.'],
        'step2_title' => ['type' => 'string', 'label' => 'Step 2 Title', 'default' => 'Design'],
        'step2_text' => ['type' => 'text', 'label' => 'Step 2 Text', 'default' => 'Our architects and engineers develop concept, schematic, and detailed designs.'],
        'step3_title' => ['type' => 'string', 'label' => 'Step 3 Title', 'default' => 'Construction'],
        'step3_text' => ['type' => 'text', 'label' => 'Step 3 Text', 'default' => 'Our project management team executes the build with strict quality and safety controls.'],
        'step4_title' => ['type' => 'string', 'label' => 'Step 4 Title', 'default' => 'Handover'],
        'step4_text' => ['type' => 'text', 'label' => 'Step 4 Text', 'default' => 'We commission, test, and hand over a complete, ready-to-use facility.'],
    ],
    'values' => [
        'value1_title' => ['type' => 'string', 'label' => 'Value 1 Title', 'default' => 'Integrity'],
        'value1_text' => ['type' => 'text', 'label' => 'Value 1 Text', 'default' => 'We do what we say. Every estimate, every schedule, and every specification we put in writing is one we stand behind on site.'],
        'value2_title' => ['type' => 'string', 'label' => 'Value 2 Title', 'default' => 'Craftsmanship'],
        'value2_text' => ['type' => 'text', 'label' => 'Value 2 Text', 'default' => 'We treat every drawing as if our own name were on the building. Precision in design work is what prevents costly surprises on the ground.'],
        'value3_title' => ['type' => 'string', 'label' => 'Value 3 Title', 'default' => 'Safety First'],
        'value3_text' => ['type' => 'text', 'label' => 'Value 3 Text', 'default' => 'No deadline is worth a compromise on site safety. Our teams are trained, certified, and empowered to stop work when something looks wrong.'],
        'value4_title' => ['type' => 'string', 'label' => 'Value 4 Title', 'default' => 'Partnership'],
        'value4_text' => ['type' => 'text', 'label' => 'Value 4 Text', 'default' => 'We see every client relationship as multi-decade, not single-project. That means honest advice, even when it costs us a change order.'],
    ],
    'story' => [
        'story1_year' => ['type' => 'string', 'label' => 'Milestone 1 Year', 'default' => '2009'],
        'story1_text' => ['type' => 'text', 'label' => 'Milestone 1 Text', 'default' => 'ACCO Private Limited is founded in Rawalpindi with a small structural engineering practice serving local residential clients.'],
        'story2_year' => ['type' => 'string', 'label' => 'Milestone 2 Year', 'default' => '2013'],
        'story2_text' => ['type' => 'text', 'label' => 'Milestone 2 Text', 'default' => 'We open our first architecture studio and win our first commercial mandate: a five-storey mixed-use tower in Lahore.'],
        'story3_year' => ['type' => 'string', 'label' => 'Milestone 3 Year', 'default' => '2016'],
        'story3_text' => ['type' => 'text', 'label' => 'Milestone 3 Text', 'default' => 'ACCO becomes a full design-build practice, bringing architecture, MEP engineering, and construction management under one roof.'],
        'story4_year' => ['type' => 'string', 'label' => 'Milestone 4 Year', 'default' => '2019'],
        'story4_text' => ['type' => 'text', 'label' => 'Milestone 4 Text', 'default' => 'We deliver our first healthcare facility, establishing a dedicated medical and clinical design practice.'],
        'story5_year' => ['type' => 'string', 'label' => 'Milestone 5 Year', 'default' => '2022'],
        'story5_text' => ['type' => 'text', 'label' => 'Milestone 5 Text', 'default' => 'ACCO crosses 100 completed projects across Pakistan and opens a second regional office in Lahore.'],
        'story6_year' => ['type' => 'string', 'label' => 'Milestone 6 Year', 'default' => '2026'],
        'story6_text' => ['type' => 'text', 'label' => 'Milestone 6 Text', 'default' => 'Today, ACCO Pakistan operates as a multidisciplinary practice of architects, engineers, and project managers delivering landmark work nationwide.'],
    ],
    'awards' => [
        'award1_title' => ['type' => 'string', 'label' => 'Award 1 Title', 'default' => 'Best Commercial Development'],
        'award1_org' => ['type' => 'string', 'label' => 'Award 1 Organization', 'default' => 'Pakistan Council of Architects & Town Planners'],
        'award1_year' => ['type' => 'string', 'label' => 'Award 1 Year', 'default' => '2025'],
        'award2_title' => ['type' => 'string', 'label' => 'Award 2 Title', 'default' => 'Excellence in Healthcare Design'],
        'award2_org' => ['type' => 'string', 'label' => 'Award 2 Organization', 'default' => 'Institute of Architects Pakistan'],
        'award2_year' => ['type' => 'string', 'label' => 'Award 2 Year', 'default' => '2024'],
        'award3_title' => ['type' => 'string', 'label' => 'Award 3 Title', 'default' => 'Sustainable Building of the Year'],
        'award3_org' => ['type' => 'string', 'label' => 'Award 3 Organization', 'default' => 'Green Building Council Pakistan'],
        'award3_year' => ['type' => 'string', 'label' => 'Award 3 Year', 'default' => '2023'],
        'award4_title' => ['type' => 'string', 'label' => 'Award 4 Title', 'default' => 'Construction Safety Excellence'],
        'award4_org' => ['type' => 'string', 'label' => 'Award 4 Organization', 'default' => 'Pakistan Engineering Council'],
        'award4_year' => ['type' => 'string', 'label' => 'Award 4 Year', 'default' => '2023'],
        'award5_title' => ['type' => 'string', 'label' => 'Award 5 Title', 'default' => 'Industrial Project of the Year'],
        'award5_org' => ['type' => 'string', 'label' => 'Award 5 Organization', 'default' => 'Federation of Pakistan Chambers of Commerce'],
        'award5_year' => ['type' => 'string', 'label' => 'Award 5 Year', 'default' => '2022'],
        'award6_title' => ['type' => 'string', 'label' => 'Award 6 Title', 'default' => 'Best Design-Build Firm — Punjab'],
        'award6_org' => ['type' => 'string', 'label' => 'Award 6 Organization', 'default' => 'Punjab Board of Investment & Trade'],
        'award6_year' => ['type' => 'string', 'label' => 'Award 6 Year', 'default' => '2021'],
    ],
    'global_presence' => [
        'office1_city' => ['type' => 'string', 'label' => 'Office 1 City', 'default' => 'Rawalpindi'],
        'office1_text' => ['type' => 'text', 'label' => 'Office 1 Description', 'default' => 'Head office and design studio, serving Rawalpindi and Islamabad since 2009.'],
        'office2_city' => ['type' => 'string', 'label' => 'Office 2 City', 'default' => 'Lahore'],
        'office2_text' => ['type' => 'text', 'label' => 'Office 2 Description', 'default' => 'Regional studio covering commercial and healthcare projects across Punjab.'],
        'office3_city' => ['type' => 'string', 'label' => 'Office 3 City', 'default' => 'Karachi'],
        'office3_text' => ['type' => 'text', 'label' => 'Office 3 Description', 'default' => 'Project delivery office supporting industrial and port-side developments in Sindh.'],
        'office4_city' => ['type' => 'string', 'label' => 'Office 4 City', 'default' => 'Faisalabad'],
        'office4_text' => ['type' => 'text', 'label' => 'Office 4 Description', 'default' => 'Site office supporting industrial and manufacturing facility projects.'],
    ],
    'industries' => [
        'industry1_title' => ['type' => 'string', 'label' => 'Industry 1 Title', 'default' => 'Commercial'],
        'industry1_text' => ['type' => 'text', 'label' => 'Industry 1 Text', 'default' => 'Offices, retail, and mixed-use towers designed for footfall, efficiency, and long-term asset value.'],
        'industry2_title' => ['type' => 'string', 'label' => 'Industry 2 Title', 'default' => 'Healthcare'],
        'industry2_text' => ['type' => 'text', 'label' => 'Industry 2 Text', 'default' => 'Hospitals and clinics engineered around clinical workflow, infection control, and patient experience.'],
        'industry3_title' => ['type' => 'string', 'label' => 'Industry 3 Title', 'default' => 'Industrial'],
        'industry3_text' => ['type' => 'text', 'label' => 'Industry 3 Text', 'default' => 'Manufacturing and logistics facilities built for throughput, safety compliance, and rapid expansion.'],
        'industry4_title' => ['type' => 'string', 'label' => 'Industry 4 Title', 'default' => 'Residential'],
        'industry4_text' => ['type' => 'text', 'label' => 'Industry 4 Text', 'default' => 'Private residences and housing developments balancing craftsmanship with livable, modern design.'],
        'industry5_title' => ['type' => 'string', 'label' => 'Industry 5 Title', 'default' => 'Hospitality'],
        'industry5_text' => ['type' => 'text', 'label' => 'Industry 5 Text', 'default' => 'Hotels and hospitality venues where architecture and interiors work together to shape guest experience.'],
        'industry6_title' => ['type' => 'string', 'label' => 'Industry 6 Title', 'default' => 'Education'],
        'industry6_text' => ['type' => 'text', 'label' => 'Industry 6 Text', 'default' => 'Campuses and academic facilities designed for daylight, acoustics, and long-term flexibility.'],
    ],
    'legal' => [
        'privacy_policy_content' => ['type' => 'text', 'label' => 'Privacy Policy Content', 'default' => "This Privacy Policy describes how ACCO Pakistan collects, uses, and protects information submitted through this website. We collect information you provide via our contact, quotation, and career forms, and use it solely to respond to your inquiry or application. We do not sell or share your information with third parties except as required to provide the services you have requested. Contact us at the email address listed on this site with any privacy questions."],
        'terms_content' => ['type' => 'text', 'label' => 'Terms & Conditions Content', 'default' => 'By using this website, you agree to use its content and services for lawful purposes only. All content, trademarks, and materials on this site are the property of ACCO Pakistan unless otherwise stated. We make reasonable efforts to keep information accurate but do not guarantee completeness. Contact us for any questions about these terms.'],
    ],
    'page_headers' => [
        'blog_header_image' => ['type' => 'image', 'label' => 'Blog Listing Page — Header Banner'],
        'services_header_image' => ['type' => 'image', 'label' => 'Services Listing Page — Header Banner'],
        'projects_header_image' => ['type' => 'image', 'label' => 'Projects Listing Page — Header Banner'],
        'about_header_image' => ['type' => 'image', 'label' => 'About Page — Header Banner'],
        'contact_header_image' => ['type' => 'image', 'label' => 'Contact Page — Header Banner'],
        'careers_header_image' => ['type' => 'image', 'label' => 'Careers Page — Header Banner'],
        'faqs_header_image' => ['type' => 'image', 'label' => 'FAQs Page — Header Banner'],
    ],
];
